apiVersion: v1
kind: PersistentVolume
metadata:
  name: vpro-pvolume
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: localdbstorage
  hostPath:
    path: "/opt/data"
